site_name: Long-read sequence analysis
nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Course material:
      - Introduction: course_material/introduction.md
      - Server login: course_material/server_login.md
      - QC and alignment: course_material/qc_alignment.md
      - Applications: course_material/applications.md
      - Group work: 
        - Introduction: course_material/group_work/group_work.md
        - Project 1: course_material/group_work/project1.md
        - Project 2: course_material/group_work/project2.md
        - Project 3: course_material/group_work/project3.md

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg
  custom_dir: overrides

# Repository
repo_name: sib-swiss/NGS-longreads-training
repo_url: https://github.com/sib-swiss/NGS-longreads-training

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our trainig material and whether users
      find what they're searching for. With your consent, you're helping us to
      make our training material better.
    cookies:
      matomo: Matomo Analytics

extra_javascript:
  - javascripts/consent.js
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
